export interface Video {
  id: string;
  title: string;
  url: string;
  category: string;
  year?: string;
  thumbnail?: string;
  description?: string;
  keywords?: string[];
}

export const videoCategories = [
  { name: "All", key: "all" },
  { name: "Software", key: "Software" },
  { name: "Medical", key: "Medical" },
  { name: "CyberScams", key: "CyberScams" },
  { name: "Science", key: "Science" },
  { name: "Career", key: "Career" },
  { name: "Creative", key: "Creative" },
  { name: "Gadgets", key: "Gadgets" },
  { name: "Defense", key: "Defense" },
  { name: "Education", key: "Education" },
];

export const allVideos: Video[] = [
  // Software & Development
  {
    id: "1",
    title: "Git Installation Latest Video",
    url: "https://www.youtube.com/watch?v=YCrXCm416mY",
    category: "Software",
    year: "2024",
    description: "Learn how to install Git version control system",
    keywords: [
      "git",
      "installation",
      "version control",
      "development",
      "setup",
      "software",
    ],
  },
  {
    id: "2",
    title: "React Hooks in Telugu Tutorial 2025",
    url: "https://www.youtube.com/watch?v=Nq5c1FtOrac",
    category: "Software",
    year: "2025",
    description: "Complete React Hooks tutorial in Telugu language",
    keywords: [
      "react",
      "hooks",
      "javascript",
      "frontend",
      "web development",
      "telugu",
      "tutorial",
    ],
  },
  {
    id: "3",
    title: "How to Run First ReactJS App Tutorial 2024",
    url: "https://www.youtube.com/watch?v=M2kV39OWfOQ",
    category: "Software",
    year: "2024",
    description:
      "Step by step guide to create and run your first React application",
    keywords: [
      "react",
      "reactjs",
      "first app",
      "tutorial",
      "javascript",
      "frontend",
      "web development",
    ],
  },
  {
    id: "4",
    title: "How to Download and Install NodeJS 2024",
    url: "https://www.youtube.com/watch?v=33O-LtTpbWU",
    category: "Software",
    year: "2024",
    description: "Complete guide to download and install Node.js",
    keywords: [
      "nodejs",
      "node",
      "javascript",
      "installation",
      "backend",
      "runtime",
      "download",
    ],
  },
  {
    id: "5",
    title: "How to Add Bootstrap in HTML 2024",
    url: "https://www.youtube.com/watch?v=a4juG-3Ky7A",
    category: "Software",
    year: "2024",
    description: "Learn to integrate Bootstrap CSS framework in HTML",
    keywords: [
      "bootstrap",
      "html",
      "css",
      "framework",
      "responsive",
      "web design",
      "frontend",
    ],
  },
  {
    id: "6",
    title: "How to Install Git Latest Video 2024",
    url: "https://www.youtube.com/watch?v=kyaA6S1HGLE",
    category: "Software",
    year: "2024",
    description: "Latest method to install Git on your system",
    keywords: [
      "git",
      "install",
      "version control",
      "github",
      "development",
      "latest",
    ],
  },
  {
    id: "7",
    title: "Eclipse IDE Download and Setup 2022",
    url: "https://www.youtube.com/watch?v=M1wL9T2bM68",
    category: "Software",
    year: "2024",
    description: "Complete Eclipse IDE setup for Java development",
    keywords: [
      "eclipse",
      "ide",
      "java",
      "development",
      "setup",
      "download",
      "programming",
    ],
  },
  {
    id: "8",
    title: "What is Web3 Technology?",
    url: "https://www.youtube.com/watch?v=K5QlZt2oNkI",
    category: "Software",
    year: "2024",
    description: "Introduction to Web3 and blockchain technology",
    keywords: [
      "web3",
      "blockchain",
      "cryptocurrency",
      "decentralized",
      "technology",
      "future",
    ],
  },
  {
    id: "9",
    title: "Difference Between Open Tags and Self Closing Tags in HTML5",
    url: "https://www.youtube.com/watch?v=fjWuphA7H4c",
    category: "Software",
    year: "2024",
    description: "Understanding HTML5 tag types and syntax",
    keywords: [
      "html5",
      "tags",
      "html",
      "web development",
      "syntax",
      "markup",
      "frontend",
    ],
  },
  {
    id: "10",
    title: "Step by Step Guide to Learn Web Development",
    url: "https://www.youtube.com/watch?v=M5bOnPzhcsg",
    category: "Software",
    year: "2024",
    description: "Complete roadmap for learning web development",
    keywords: [
      "web development",
      "guide",
      "roadmap",
      "learning",
      "frontend",
      "backend",
      "programming",
    ],
  },
  {
    id: "11",
    title: "How to Insert Image in HTML",
    url: "https://www.youtube.com/watch?v=SOALcgA52qk",
    category: "Software",
    year: "2024",
    description: "Learn to add images in HTML documents",
    keywords: [
      "html",
      "image",
      "img tag",
      "web development",
      "markup",
      "frontend",
    ],
  },
  {
    id: "12",
    title: "Best Code Editor for Professionals",
    url: "https://www.youtube.com/watch?v=vj3nBnlwZP8",
    category: "Software",
    year: "2024",
    description: "Review of best code editors for developers",
    keywords: [
      "code editor",
      "vscode",
      "programming",
      "development",
      "tools",
      "ide",
    ],
  },
  {
    id: "13",
    title: "How to Change Themes in Microsoft Word 2024",
    url: "https://www.youtube.com/watch?v=JcdnwMjqCkA",
    category: "Software",
    year: "2024",
    description: "Customize Microsoft Word with different themes",
    keywords: [
      "microsoft word",
      "word",
      "themes",
      "office",
      "customization",
      "tutorial",
    ],
  },
  {
    id: "14",
    title: "Insert Image with Single Click in MS Word",
    url: "https://www.youtube.com/watch?v=DJF8yAhiL-o",
    category: "Software",
    year: "2024",
    description: "Quick way to insert images in Microsoft Word",
    keywords: [
      "microsoft word",
      "word",
      "image",
      "insert",
      "office",
      "tutorial",
    ],
  },

  // Medical Coding
  {
    id: "15",
    title: "Medical Coding Course Part 1",
    url: "https://www.youtube.com/watch?v=N7jZxShJ3uI",
    category: "Medical",
    year: "2024",
    description: "Introduction to medical coding fundamentals",
    keywords: [
      "medical coding",
      "healthcare",
      "ICD",
      "course",
      "training",
      "certification",
    ],
  },
  {
    id: "16",
    title: "Pregnancy Guidelines Part 2 in Telugu 2025",
    url: "https://www.youtube.com/watch?v=ue2K1Ud8oDY",
    category: "Medical",
    year: "2025",
    description: "Medical coding guidelines for pregnancy cases",
    keywords: [
      "pregnancy",
      "medical coding",
      "guidelines",
      "telugu",
      "obstetrics",
      "coding",
    ],
  },
  {
    id: "17",
    title: "HIV and AIDS Coding Tips 2025",
    url: "https://www.youtube.com/watch?v=74dHD1PeSWo",
    category: "Medical",
    year: "2025",
    description: "Coding guidelines for HIV and AIDS cases",
    keywords: [
      "hiv",
      "aids",
      "medical coding",
      "infectious disease",
      "coding tips",
      "healthcare",
    ],
  },
  {
    id: "18",
    title: "Coding Tips for Pregnancy Chart in Telugu 2025",
    url: "https://www.youtube.com/watch?v=2iP9cT3u2ho",
    category: "Medical",
    year: "2025",
    description: "How to code pregnancy charts correctly",
    keywords: [
      "pregnancy",
      "chart",
      "medical coding",
      "telugu",
      "obstetrics",
      "coding tips",
    ],
  },
  {
    id: "19",
    title: "Pregnancy Trimesters 2025",
    url: "https://www.youtube.com/watch?v=IUuSj9EqpOo",
    category: "Medical",
    year: "2025",
    description: "Understanding pregnancy trimesters in medical coding",
    keywords: [
      "pregnancy",
      "trimesters",
      "medical coding",
      "obstetrics",
      "healthcare",
    ],
  },
  {
    id: "20",
    title: "Pregnancy Guidelines in Telugu 2025",
    url: "https://www.youtube.com/watch?v=8kTBqURpRwY",
    category: "Medical",
    year: "2025",
    description: "Complete pregnancy coding guidelines",
    keywords: [
      "pregnancy",
      "guidelines",
      "medical coding",
      "telugu",
      "obstetrics",
    ],
  },
  {
    id: "21",
    title: "Psychiatric Conditions in Medical Coding 2025",
    url: "https://www.youtube.com/watch?v=ShSw7jTE9-A",
    category: "Medical",
    year: "2025",
    description: "How to code psychiatric and mental health conditions",
    keywords: [
      "psychiatric",
      "mental health",
      "medical coding",
      "psychology",
      "conditions",
    ],
  },
  {
    id: "22",
    title: "MEAT Concept in Telugu Medical Coding 2024",
    url: "https://www.youtube.com/watch?v=DuefJIcbVdY",
    category: "Medical",
    year: "2024",
    description: "Understanding MEAT concept in medical coding",
    keywords: [
      "meat concept",
      "medical coding",
      "telugu",
      "healthcare",
      "documentation",
    ],
  },
  {
    id: "23",
    title: "Conflicts for Diabetes Mellitus Part 1 - 2024",
    url: "https://www.youtube.com/watch?v=Ct0b7mHe6ns",
    category: "Medical",
    year: "2024",
    description: "Resolving coding conflicts in diabetes cases",
    keywords: [
      "diabetes",
      "diabetes mellitus",
      "medical coding",
      "conflicts",
      "healthcare",
    ],
  },
  {
    id: "24",
    title: "Types of DM and its Complications 2024",
    url: "https://www.youtube.com/watch?v=iS6f-g-Z-1U",
    category: "Medical",
    year: "2024",
    description: "Different types of diabetes and complications",
    keywords: [
      "diabetes",
      "dm",
      "complications",
      "medical coding",
      "types",
      "healthcare",
    ],
  },
  {
    id: "25",
    title: "BMI Coding 2024 - Obesity",
    url: "https://www.youtube.com/watch?v=Klf60A_WRpA",
    category: "Medical",
    year: "2024",
    description: "How to code BMI and obesity conditions",
    keywords: [
      "bmi",
      "obesity",
      "medical coding",
      "weight",
      "body mass index",
      "healthcare",
    ],
  },
  {
    id: "26",
    title: "How to Process a Patient Chart in Medical Coding 2024",
    url: "https://www.youtube.com/watch?v=rVLDVKYdSbA",
    category: "Medical",
    year: "2024",
    description: "Step by step patient chart processing",
    keywords: [
      "patient chart",
      "chart processing",
      "medical coding",
      "healthcare",
      "documentation",
    ],
  },
  {
    id: "27",
    title: "Chart Identification in Medical Coding 2024",
    url: "https://www.youtube.com/watch?v=NdIMt8pjxPM",
    category: "Medical",
    year: "2024",
    description: "How to identify different types of medical charts",
    keywords: [
      "chart identification",
      "medical coding",
      "chart types",
      "healthcare",
      "documentation",
    ],
  },
  {
    id: "28",
    title: "Medical Terminology: Suffixes Made Easy 2024",
    url: "https://www.youtube.com/watch?v=mBaQl_vLSlc",
    category: "Medical",
    year: "2024",
    description: "Understanding medical terminology suffixes",
    keywords: [
      "medical terminology",
      "suffixes",
      "healthcare",
      "medical coding",
      "language",
    ],
  },

  // CyberScams & Security
  {
    id: "29",
    title: "Be Aware of Sextortion and Blackmail Scams",
    url: "https://www.youtube.com/watch?v=FAYfRD9jnDs",
    category: "CyberScams",
    year: "2024",
    description: "Stay safe from sextortion and blackmail scams",
    keywords: [
      "sextortion",
      "blackmail",
      "cybersecurity",
      "scams",
      "safety",
      "awareness",
    ],
  },
  {
    id: "30",
    title: "Sextortion Explanation in Telugu",
    url: "https://www.youtube.com/watch?v=wBUtiufAUsk",
    category: "CyberScams",
    year: "2024",
    description: "Understanding sextortion scams in Telugu",
    keywords: [
      "sextortion",
      "telugu",
      "cybersecurity",
      "scams",
      "awareness",
      "safety",
    ],
  },
  {
    id: "31",
    title: "Cyber Crimes Attacks Explained in Telugu",
    url: "https://www.youtube.com/watch?v=ukgk8DldqL0",
    category: "CyberScams",
    year: "2024",
    description: "Types of cyber crime attacks explained",
    keywords: [
      "cyber crimes",
      "cyber attacks",
      "telugu",
      "cybersecurity",
      "hacking",
      "security",
    ],
  },
  {
    id: "32",
    title: "What is Phishing Attack and Types of Email Scams",
    url: "https://www.youtube.com/watch?v=EeKi6msUr28",
    category: "CyberScams",
    year: "2024",
    description: "Understanding phishing attacks and email scams",
    keywords: [
      "phishing",
      "email scams",
      "cybersecurity",
      "fraud",
      "security",
      "awareness",
    ],
  },
  {
    id: "33",
    title: "Uninstall GB WhatsApp - Use WhatsApp Only",
    url: "https://www.youtube.com/watch?v=cGNH94OmxVs",
    category: "CyberScams",
    year: "2024",
    description: "Why you should avoid GB WhatsApp and use official WhatsApp",
    keywords: [
      "gb whatsapp",
      "whatsapp",
      "security",
      "privacy",
      "malware",
      "safety",
    ],
  },
  {
    id: "34",
    title: "Dark Web Monitoring in Gmail - Data Breach Protection",
    url: "https://www.youtube.com/watch?v=VEq9C_vQF6I",
    category: "CyberScams",
    year: "2024",
    description: "Enable dark web monitoring for Gmail security",
    keywords: [
      "dark web",
      "gmail",
      "data breach",
      "monitoring",
      "security",
      "protection",
    ],
  },
  {
    id: "35",
    title: "What is Data Breach Awareness",
    url: "https://www.youtube.com/watch?v=eHhCFOIBItw",
    category: "CyberScams",
    year: "2024",
    description: "Understanding data breaches and protection",
    keywords: [
      "data breach",
      "cybersecurity",
      "privacy",
      "security",
      "awareness",
      "protection",
    ],
  },
  {
    id: "36",
    title: "The Truth About Honey Trap Awareness",
    url: "https://www.youtube.com/watch?v=oUW9sgHYF6g",
    category: "CyberScams",
    year: "2024",
    description: "Understanding honey trap scams and how to avoid them",
    keywords: [
      "honey trap",
      "scams",
      "cybersecurity",
      "awareness",
      "social engineering",
      "safety",
    ],
  },
  {
    id: "37",
    title: "How to Add Recovery Mail to Gmail 2024",
    url: "https://www.youtube.com/watch?v=r_1P_RYPibU",
    category: "CyberScams",
    year: "2024",
    description: "Secure your Gmail with recovery email",
    keywords: [
      "gmail",
      "recovery email",
      "security",
      "account protection",
      "google",
      "safety",
    ],
  },
  {
    id: "38",
    title: "Gmail Check All Your Devices 2024",
    url: "https://www.youtube.com/watch?v=CsUNVOEAxFA",
    category: "CyberScams",
    year: "2024",
    description: "Monitor all devices connected to your Gmail",
    keywords: [
      "gmail",
      "devices",
      "security",
      "monitoring",
      "google",
      "account safety",
    ],
  },
  {
    id: "39",
    title: "Kids with Cellphones at Higher Risk of Cyber Bullying",
    url: "https://www.youtube.com/watch?v=BCiRW9M9U68",
    category: "CyberScams",
    year: "2024",
    description: "Protecting children from cyberbullying",
    keywords: [
      "cyber bullying",
      "kids",
      "children",
      "safety",
      "parental control",
      "awareness",
    ],
  },
  {
    id: "40",
    title: "Common Types of Cyber Attacks",
    url: "https://www.youtube.com/watch?v=HeEIjgYrmMU",
    category: "CyberScams",
    year: "2024",
    description: "Overview of common cyber attack methods",
    keywords: [
      "cyber attacks",
      "hacking",
      "cybersecurity",
      "security",
      "malware",
      "threats",
    ],
  },
  {
    id: "41",
    title: "Dangerous Malwares 2022",
    url: "https://www.youtube.com/watch?v=KLTA688mxt8",
    category: "CyberScams",
    year: "2022",
    description: "Types of dangerous malware and protection",
    keywords: [
      "malware",
      "virus",
      "cybersecurity",
      "threats",
      "protection",
      "antivirus",
    ],
  },
  {
    id: "42",
    title: "Keyloggers Explained",
    url: "https://www.youtube.com/watch?v=3qJDiPh4-zY",
    category: "CyberScams",
    year: "2024",
    description: "Understanding keylogger threats and protection",
    keywords: [
      "keylogger",
      "spyware",
      "cybersecurity",
      "password theft",
      "malware",
      "protection",
    ],
  },
  {
    id: "43",
    title: "Use of Virtual Keyboards in Net Banking",
    url: "https://www.youtube.com/watch?v=Pxl_cAqC20w",
    category: "CyberScams",
    year: "2024",
    description: "How virtual keyboards protect online banking",
    keywords: [
      "virtual keyboard",
      "net banking",
      "online banking",
      "security",
      "keylogger protection",
    ],
  },
  {
    id: "44",
    title: "WhatsApp vs GB WhatsApp",
    url: "https://www.youtube.com/watch?v=lSQyKNl-XEw",
    category: "CyberScams",
    year: "2024",
    description: "Comparison between official WhatsApp and GB WhatsApp",
    keywords: [
      "whatsapp",
      "gb whatsapp",
      "security",
      "privacy",
      "comparison",
      "safety",
    ],
  },

  // Science & Technology
  {
    id: "45",
    title: "DeepSeek AI - Trump Warns of Wake-up Call",
    url: "https://www.youtube.com/watch?v=tS-m7CiAwSM",
    category: "Science",
    year: "2025",
    description: "Latest developments in DeepSeek AI technology",
    keywords: [
      "deepseek",
      "ai",
      "artificial intelligence",
      "technology",
      "news",
      "latest",
    ],
  },
  {
    id: "46",
    title: "DeepSeek AI vs ChatGPT - Who Wins?",
    url: "https://www.youtube.com/watch?v=WUebh8yL_1U",
    category: "Science",
    year: "2025",
    description: "Comparison between DeepSeek AI and ChatGPT",
    keywords: [
      "deepseek",
      "chatgpt",
      "ai",
      "artificial intelligence",
      "comparison",
      "technology",
    ],
  },
  {
    id: "47",
    title: "Why Chandrayaan 3 is Important to India",
    url: "https://www.youtube.com/watch?v=JOOgkr9zDcY",
    category: "Science",
    year: "2024",
    description: "Significance of Chandrayaan 3 mission for India",
    keywords: [
      "chandrayaan",
      "space",
      "isro",
      "india",
      "moon mission",
      "space exploration",
    ],
  },
  {
    id: "48",
    title: "Chandrayaan 3 Lander Makes Successful Soft Landing",
    url: "https://www.youtube.com/watch?v=FWioVWNbEwo",
    category: "Science",
    year: "2024",
    description: "Historic soft landing of Chandrayaan 3",
    keywords: [
      "chandrayaan",
      "soft landing",
      "moon",
      "isro",
      "space",
      "achievement",
    ],
  },
  {
    id: "49",
    title: "Elon Musk Neuralink Brain Chip Implant",
    url: "https://www.youtube.com/watch?v=om4inGelcp0",
    category: "Science",
    year: "2024",
    description: "Neuralink brain chip technology explained",
    keywords: [
      "neuralink",
      "brain chip",
      "elon musk",
      "neurotechnology",
      "implant",
      "future tech",
    ],
  },
  {
    id: "50",
    title: "Elon Musk Neuralink Brain Implant - First Telepathy Chip",
    url: "https://www.youtube.com/watch?v=S04iKAb4dx4",
    category: "Science",
    year: "2024",
    description: "First telepathy chip from Neuralink",
    keywords: [
      "neuralink",
      "telepathy",
      "brain chip",
      "elon musk",
      "neurotechnology",
      "breakthrough",
    ],
  },
  {
    id: "51",
    title: "Google New AI Tool",
    url: "https://www.youtube.com/watch?v=OCDN566K8xM",
    category: "Science",
    year: "2024",
    description: "Latest AI tools from Google",
    keywords: [
      "google",
      "ai",
      "artificial intelligence",
      "tools",
      "technology",
      "innovation",
    ],
  },
  {
    id: "52",
    title: "Augmented Reality in 1 Minute",
    url: "https://www.youtube.com/watch?v=z9lnL4JR8n4",
    category: "Science",
    year: "2024",
    description: "Quick explanation of Augmented Reality",
    keywords: [
      "augmented reality",
      "ar",
      "virtual reality",
      "technology",
      "innovation",
      "future",
    ],
  },
  {
    id: "53",
    title: "Samsung Galaxy AI Assistant #CES2024",
    url: "https://www.youtube.com/watch?v=Hk48IlQKIW4",
    category: "Science",
    year: "2024",
    description: "Samsung Galaxy AI features from CES 2024",
    keywords: [
      "samsung",
      "galaxy ai",
      "ces2024",
      "ai assistant",
      "technology",
      "innovation",
    ],
  },
  {
    id: "54",
    title: "Upcoming Artificial Intelligence by Google",
    url: "https://www.youtube.com/watch?v=QNuJnxk15Ro",
    category: "Science",
    year: "2024",
    description: "Future AI developments from Google",
    keywords: [
      "google",
      "artificial intelligence",
      "ai",
      "future technology",
      "innovation",
      "development",
    ],
  },
  {
    id: "55",
    title: "Future Technology of Organoid Cells",
    url: "https://www.youtube.com/watch?v=2HL3khIZKVM",
    category: "Science",
    year: "2024",
    description: "Organoid cell technology and its future",
    keywords: [
      "organoid",
      "cells",
      "biotechnology",
      "medical technology",
      "future",
      "research",
    ],
  },
  {
    id: "56",
    title: "ChatGPT Warning System on Bioweapons",
    url: "https://www.youtube.com/watch?v=PWLOUdEVrr4",
    category: "Science",
    year: "2024",
    description: "ChatGPT safety measures for bioweapon discussions",
    keywords: [
      "chatgpt",
      "bioweapons",
      "ai safety",
      "warning system",
      "security",
      "ethics",
    ],
  },
  {
    id: "57",
    title: "Launch of PSLV-C57/Aditya-L1 Mission",
    url: "https://www.youtube.com/watch?v=KkAaHSty720",
    category: "Science",
    year: "2024",
    description: "ISRO Aditya-L1 solar mission launch",
    keywords: [
      "aditya l1",
      "pslv",
      "isro",
      "solar mission",
      "space",
      "sun study",
    ],
  },
  {
    id: "58",
    title: "Samsung Launches AI Food and Recipe Service",
    url: "https://www.youtube.com/watch?v=CATeWESOtw4",
    category: "Science",
    year: "2024",
    description: "Samsung AI for food and recipes",
    keywords: ["samsung", "ai", "food", "recipe", "cooking", "smart kitchen"],
  },

  // Career & Jobs
  {
    id: "59",
    title: "How to Add Upwork Withdrawal Bank Account",
    url: "https://www.youtube.com/watch?v=093smeLTJ50",
    category: "Career",
    year: "2024",
    description: "Setup bank account for Upwork withdrawals",
    keywords: [
      "upwork",
      "freelance",
      "withdrawal",
      "bank account",
      "payment",
      "freelancing",
    ],
  },
  {
    id: "60",
    title: "Latest Job Notification TCS 2024",
    url: "https://www.youtube.com/watch?v=xkamoggx4AA",
    category: "Career",
    year: "2024",
    description: "TCS job openings and notifications",
    keywords: ["tcs", "job", "notification", "career", "hiring", "it jobs"],
  },
  {
    id: "61",
    title: "Latest Job Notification Amazon ML Data Associate",
    url: "https://www.youtube.com/watch?v=2ip7wtiDVgQ",
    category: "Career",
    year: "2024",
    description: "Amazon ML Data Associate job opportunities",
    keywords: [
      "amazon",
      "ml",
      "machine learning",
      "data associate",
      "job",
      "career",
    ],
  },
  {
    id: "62",
    title: "How to Get Daily Corp to Corp Requirements",
    url: "https://www.youtube.com/watch?v=yMjyW1UBZhY",
    category: "Career",
    year: "2024",
    description: "Finding corp to corp job requirements",
    keywords: [
      "corp to corp",
      "c2c",
      "requirements",
      "contract",
      "job",
      "consulting",
    ],
  },

  // Creative & Tools
  {
    id: "63",
    title: "Memes Creation for YouTube or Instagram",
    url: "https://www.youtube.com/watch?v=GJupjUI72n0",
    category: "Creative",
    year: "2024",
    description: "How to create memes for social media",
    keywords: [
      "memes",
      "creation",
      "youtube",
      "instagram",
      "social media",
      "content creation",
    ],
  },
  {
    id: "64",
    title: "Amazing AI Meme Generator",
    url: "https://www.youtube.com/watch?v=FXrc_CCJ1Z8",
    category: "Creative",
    year: "2024",
    description: "AI tools for generating memes",
    keywords: [
      "ai",
      "meme generator",
      "artificial intelligence",
      "content creation",
      "automation",
    ],
  },
  {
    id: "65",
    title: "Text Animation Basics in Blender",
    url: "https://www.youtube.com/watch?v=4DNh5ptfq7s",
    category: "Creative",
    year: "2024",
    description: "Creating text animations in Blender 3D",
    keywords: [
      "blender",
      "text animation",
      "3d",
      "animation",
      "motion graphics",
      "tutorial",
    ],
  },
  {
    id: "66",
    title: "Free Video Editing Software Online",
    url: "https://www.youtube.com/watch?v=ICpvZCJDYds",
    category: "Creative",
    year: "2024",
    description: "Best free online video editing tools",
    keywords: [
      "video editing",
      "free software",
      "online tools",
      "editing",
      "content creation",
    ],
  },
  {
    id: "67",
    title: "Free Versions and Open Source Software Access",
    url: "https://www.youtube.com/watch?v=_M3Z1fymtkA",
    category: "Creative",
    year: "2024",
    description: "Finding free and open source software alternatives",
    keywords: [
      "free software",
      "open source",
      "alternative software",
      "budget tools",
      "accessibility",
    ],
  },

  // Gadgets & Devices
  {
    id: "68",
    title: "iPhone Lockdown Mode",
    url: "https://www.youtube.com/watch?v=SjoSc3Znnpk",
    category: "Gadgets",
    year: "2024",
    description: "iPhone Lockdown Mode for enhanced security",
    keywords: [
      "iphone",
      "lockdown mode",
      "security",
      "apple",
      "privacy",
      "protection",
    ],
  },
  {
    id: "69",
    title: "Review of Brave Browser 2024",
    url: "https://www.youtube.com/watch?v=lNZypeKYrAE",
    category: "Gadgets",
    year: "2024",
    description: "Complete review of Brave browser",
    keywords: [
      "brave browser",
      "browser",
      "privacy",
      "security",
      "review",
      "web browsing",
    ],
  },
  {
    id: "70",
    title: "Apple Watch Series 8 2022",
    url: "https://www.youtube.com/watch?v=A4SwbDrFgB4",
    category: "Gadgets",
    year: "2022",
    description: "Apple Watch Series 8 features and review",
    keywords: [
      "apple watch",
      "series 8",
      "smartwatch",
      "apple",
      "wearable",
      "fitness",
    ],
  },
  {
    id: "71",
    title: "Realme Book Review",
    url: "https://www.youtube.com/watch?v=dRI8fUuSxDM",
    category: "Gadgets",
    year: "2024",
    description: "Comprehensive review of Realme Book laptop",
    keywords: [
      "realme book",
      "laptop",
      "review",
      "realme",
      "computer",
      "performance",
    ],
  },
  {
    id: "72",
    title: "New MacBook Air 2022 M2 Chip",
    url: "https://www.youtube.com/watch?v=xRRO5AJL6Xk",
    category: "Gadgets",
    year: "2022",
    description: "MacBook Air with M2 chip features",
    keywords: [
      "macbook air",
      "m2 chip",
      "apple",
      "laptop",
      "performance",
      "review",
    ],
  },

  // Defense & Military
  {
    id: "73",
    title: "Indian Army Operation Sindoor - Precision Strikes",
    url: "https://www.youtube.com/watch?v=EFuVQihdCeM",
    category: "Defense",
    year: "2024",
    description: "Indian Army military operation overview",
    keywords: [
      "indian army",
      "operation sindoor",
      "military",
      "defense",
      "precision strikes",
      "strategy",
    ],
  },
  {
    id: "74",
    title: "Kolkata Doctor Case - Dr Subarna Goswami",
    url: "https://www.youtube.com/watch?v=qpGpQe8sj6w",
    category: "Defense",
    year: "2024",
    description: "Analysis of Kolkata doctor case",
    keywords: [
      "kolkata",
      "doctor",
      "case study",
      "medical",
      "legal",
      "healthcare",
    ],
  },

  // Education
  {
    id: "75",
    title: "How to Apply UPSC Application in Telugu",
    url: "https://www.youtube.com/watch?v=i3eGBVZEDXM",
    category: "Education",
    year: "2024",
    description: "UPSC application process in Telugu",
    keywords: [
      "upsc",
      "application",
      "telugu",
      "civil services",
      "government jobs",
      "exam",
    ],
  },
  {
    id: "76",
    title: "How to Apply RBI Office Attendants Posts 2021",
    url: "https://www.youtube.com/watch?v=XQTDdyZg6P8",
    category: "Education",
    year: "2021",
    description: "RBI office attendant job application process",
    keywords: [
      "rbi",
      "office attendant",
      "application",
      "bank jobs",
      "government",
      "recruitment",
    ],
  },
  {
    id: "77",
    title: "How to Apply SSC Job Application in Telugu",
    url: "https://www.youtube.com/watch?v=7vplLVLRBn0",
    category: "Education",
    year: "2024",
    description: "SSC job application process in Telugu",
    keywords: [
      "ssc",
      "job application",
      "telugu",
      "government jobs",
      "staff selection",
      "exam",
    ],
  },
  {
    id: "78",
    title: "BSC Military Nursing Admission",
    url: "https://www.youtube.com/watch?v=LXoyGKAIYwU",
    category: "Education",
    year: "2024",
    description: "BSC Military Nursing admission process",
    keywords: [
      "bsc",
      "military nursing",
      "admission",
      "nursing",
      "medical education",
      "defense",
    ],
  },
];

// Enhanced search keywords for better discovery
export const searchKeywords = [
  // Software & Development
  "react",
  "javascript",
  "html",
  "css",
  "git",
  "nodejs",
  "bootstrap",
  "eclipse",
  "web development",
  "programming",
  "code editor",
  "microsoft word",
  "tutorial",
  "frontend",
  "backend",
  "ide",
  "version control",
  "github",
  "responsive design",
  "web3",
  "blockchain",
  "framework",
  "markup",
  "syntax",

  // Medical Coding
  "medical coding",
  "pregnancy",
  "diabetes",
  "bmi",
  "obesity",
  "hiv",
  "aids",
  "psychiatric",
  "meat concept",
  "chart",
  "terminology",
  "suffixes",
  "icd",
  "healthcare",
  "obstetrics",
  "coding tips",
  "documentation",
  "patient chart",
  "chart processing",
  "chart identification",
  "complications",
  "dm",

  // CyberScams & Security
  "cybersecurity",
  "phishing",
  "sextortion",
  "malware",
  "data breach",
  "gmail security",
  "whatsapp",
  "keylogger",
  "virtual keyboard",
  "honey trap",
  "cyber attacks",
  "hacking",
  "security",
  "privacy",
  "fraud",
  "scams",
  "blackmail",
  "awareness",
  "protection",
  "antivirus",
  "spyware",

  // Science & Technology
  "ai",
  "artificial intelligence",
  "chatgpt",
  "deepseek",
  "chandrayaan",
  "space",
  "neuralink",
  "brain chip",
  "augmented reality",
  "samsung",
  "google",
  "organoid",
  "isro",
  "moon mission",
  "telepathy",
  "future tech",
  "innovation",
  "biotechnology",
  "neurotechnology",
  "breakthrough",

  // Career & Jobs
  "job",
  "career",
  "tcs",
  "amazon",
  "upwork",
  "freelance",
  "corp to corp",
  "requirements",
  "hiring",
  "it jobs",
  "machine learning",
  "data associate",
  "consulting",
  "contract",
  "c2c",
  "freelancing",
  "payment",

  // Creative & Tools
  "memes",
  "creation",
  "blender",
  "video editing",
  "animation",
  "content creation",
  "social media",
  "youtube",
  "instagram",
  "ai tools",
  "automation",
  "motion graphics",
  "free software",
  "open source",
  "budget tools",

  // Gadgets & Devices
  "iphone",
  "apple watch",
  "macbook",
  "brave browser",
  "realme book",
  "lockdown mode",
  "smartwatch",
  "laptop",
  "m2 chip",
  "performance",
  "review",
  "wearable",
  "fitness",
  "computer",

  // Education & Government
  "upsc",
  "ssc",
  "rbi",
  "government jobs",
  "civil services",
  "exam",
  "application",
  "recruitment",
  "bank jobs",
  "staff selection",
  "military nursing",
  "admission",
  "nursing",
  "medical education",

  // Languages
  "telugu",
  "hindi",
  "english",
];

// Popular search suggestions
export const popularSearches = [
  "React tutorial",
  "Medical coding",
  "Cybersecurity tips",
  "ChatGPT vs DeepSeek",
  "Git installation",
  "Pregnancy coding",
  "Phishing attacks",
  "Job opportunities",
  "iPhone security",
  "Web development guide",
];
