name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Format Check
        run: npx prettier --check "src/**/*.{js,jsx,ts,tsx,json,css,md}"
      - name: Build
        run: npm run build 